# Generated by Django 4.2.9 on 2024-01-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_cars_options_alter_cars_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/% Y/% m/% d/'),
        ),
    ]
